spring.application.name=api-gateway
server.port=8080

eureka.client.serviceUrl.defaultZone=http://localhost:8762/eureka/

# Enable discovery locator
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ========================
# MANUAL ROUTING (FIXED)
# ========================

# USER SERVICE
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/user/(?<segment>.*), /${segment}

# PRODUCT SERVICE
spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://product-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/product/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/product/(?<segment>.*), /${segment}

# PAYMENT SERVICE
spring.cloud.gateway.routes[2].id=payment-service
spring.cloud.gateway.routes[2].uri=lb://payment-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/payment/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/payment/(?<segment>.*), /${segment}